#!/bin/bash
set -eu

APP_CODE="/app/code"

source "${APP_CODE}/env.sh"

mkdir -p /app/data /run \
  /app/data/cdn/users \
  /app/data/cdn/temp/users \
  /app/data/cdn/properties \
  /app/data/cdn/temp/properties \
  /app/data/cdn/locations \
  /app/data/cdn/temp/locations

# Do not chown to cloudron; that user does not exist in this image.
# If permissions become an issue later, we can create an explicit app user in Dockerfile.cloudron.

cat > "${APP_CODE}/backend/.env" <<EOF
NODE_ENV=${NODE_ENV}
MI_WEBSITE_NAME=${MI_WEBSITE_NAME}
MI_PORT=${MI_PORT}
MI_HTTPS=${MI_HTTPS}

MI_DB_URI=${MI_DB_URI}
MI_DB_SSL=${MI_DB_SSL}
MI_DB_DEBUG=${MI_DB_DEBUG}
MI_DB_SERVER_SIDE_JAVASCRIPT=${MI_DB_SERVER_SIDE_JAVASCRIPT}

MI_COOKIE_SECRET=${MI_COOKIE_SECRET}
MI_AUTH_COOKIE_DOMAIN=${MI_AUTH_COOKIE_DOMAIN}
MI_JWT_SECRET=${MI_JWT_SECRET}

MI_SMTP_HOST=${MI_SMTP_HOST}
MI_SMTP_PORT=${MI_SMTP_PORT}
MI_SMTP_USER=${MI_SMTP_USER}
MI_SMTP_PASS=${MI_SMTP_PASS}
MI_SMTP_FROM=${MI_SMTP_FROM}

MI_CDN_ROOT=${MI_CDN_ROOT}
MI_CDN_USERS=${MI_CDN_USERS}
MI_CDN_TEMP_USERS=${MI_CDN_TEMP_USERS}
MI_CDN_PROPERTIES=${MI_CDN_PROPERTIES}
MI_CDN_TEMP_PROPERTIES=${MI_CDN_TEMP_PROPERTIES}
MI_CDN_LOCATIONS=${MI_CDN_LOCATIONS}
MI_CDN_TEMP_LOCATIONS=${MI_CDN_TEMP_LOCATIONS}

MI_ADMIN_HOST=${MI_ADMIN_HOST}
MI_FRONTEND_HOST=${MI_FRONTEND_HOST}

MI_DEFAULT_LANGUAGE=${MI_DEFAULT_LANGUAGE}
MI_MINIMUM_AGE=${MI_MINIMUM_AGE}
MI_TIMEZONE=${MI_TIMEZONE}
MI_STRIPE_SECRET_KEY=${MI_STRIPE_SECRET_KEY}
MI_PAYPAL_SANDBOX=${MI_PAYPAL_SANDBOX}
MI_PAYPAL_CLIENT_ID=${MI_PAYPAL_CLIENT_ID}
MI_PAYPAL_CLIENT_SECRET=${MI_PAYPAL_CLIENT_SECRET}
MI_ADMIN_EMAIL=${MI_ADMIN_EMAIL}
EOF

cd "${APP_CODE}/backend"
exec npm run start:setup